function getRandomCity() {
    const cities = [  "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "San Francisco",
    "Charlotte",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Boston",
    "Nashville",
    "El Paso",
    "Detroit",
    "Memphis",
    "Portland",
    "Oklahoma City",
    "Las Vegas",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Mesa",
    "Atlanta",
    "Kansas City",
    "Colorado Springs",
    "Miami",
    "Raleigh",
    "Omaha",
    "Long Beach",
    "Virginia Beach",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Wichita",
    "New Orleans",
    "Arlington",
    "Tampa",
    "Aurora",
    "Santa Ana",
    "St. Louis",
    "Pittsburgh",
    "Corpus Christi",
    "Riverside",
    "Cincinnati",
    "Lexington",
    "Anchorage",
    "Stockton",
    "Toledo",
    "St. Paul",
    "Newark",
    "Greensboro",
    "Buffalo",
    "Plano",
    "Lincoln",
    "Henderson",
    "Fort Wayne",
    "Jersey City",
    "St. Petersburg",
    "Chula Vista",
    "Norfolk",
    "Orlando",
    "Chandler",
    "Laredo",
    "Madison",
    "Winston-Salem",
    "Lubbock",
    "Baton Rouge",
    "Durham",
    "Garland",
    "Glendale",
    "Reno",
    "Hialeah",
    "Chesapeake",
    "Scottsdale",
    "North Las Vegas",
    "Irving",
    "Fremont",
    "Irvine",
    "Birmingham",
    "Rochester",
    "San Bernardino",
    "Spokane",
    "Gilbert",
    "Arlington",
    "Montgomery",
    "Boise",
    "Richmond",
    "Des Moines",
    "Modesto",
    "Fayetteville",
    "Shreveport",
    "Akron",
    "Tacoma",
    "Aurora",
    "Oxnard",
    "Fontana",
    "Yonkers",
    "Augusta",
    "Mobile",
    "Little Rock",
    "Moreno Valley",
    "Glendale",
    "Amarillo",
    "Huntington Beach",
    "Columbus",
    "Grand Rapids",
    "Salt Lake City",
    "Tallahassee",
    "Worcester",
    "Newport News",
    "Huntsville",
    "Knoxville",
    "Providence",
    "Santa Clarita",
    "Grand Prairie",
    "Brownsville",
    "Jackson",
    "Overland Park",
    "Garden Grove",
    "Santa Rosa",
    "Chattanooga",
    "Oceanside",
    "Fort Lauderdale",
    "Rancho Cucamonga",
    "Port St. Lucie",
    "Tempe",
    "Ontario"];
    return cities[Math.floor(Math.random() * cities.length)];
  }
  
  export { getRandomCity };